### ISSUE TITLE
Webpack build generates failing code in goban.js (self is undefined)

### ISSUE THREAD

**Issue by adamreisnz** [online-go/goban#171]
Hello, webpack seems to generate failing code for this library.
The source of `build/goban.js` contains the following:

```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
		exports["goban"] = factory();
	else
		root["goban"] = factory();
})(self, () => {
```

The problem is on the last line, with `self`, and more specifically when importing this module in Nuxt this fails with:

```
self is not defined
   at ./goban:26:4
```

Looking at https://github.com/webpack/webpack/issues/6784, it seems to be a Webpack issue.

The code should instead be:

```
typeof self !== 'undefined' ? self : this
```

Can you please update Webpack version to resolve this, or otherwise manually modify the output build in the library to prevent this error.

Better yet, it would be awesome if there would be just a mjs export with no need for webpack.

Many thanks!

**Comment by anoek** [comment]
We're well past that webpack version, so I don't think that's it.

Are you using this in node context or a web context?

**Comment by adamreisnz** [comment]
Web context, in Nuxt.
The behaviour is very erratic. Sometimes it loads ok, then after a HMR it fails, and sometimes it doesn't work at all until I comment out the import `import {GobanSocket} from 'goban'` altogether =/

**Comment by adamreisnz** [comment]
I've wrapped the relevant components with `<ClientOnly>` tags for now and I think that may resolve it for the time being

**Comment by anoek** [comment]
Hmm, that sounds more like an issue with Nuxt if it works sometimes? 

https://github.com/online-go/goban/blob/main/webpack.config.js#L123-L130

This is where we tell Weboack how to bundle the goban library, you can try adding something like `globalObject: 'this'` to the `output` object and see if it changes anything for you but I don't think it will since it "works sometimes".

You can also try some different library types. We had it on UMD because we used to link this to both node and web, but now that `goban-engine` is split off we have some more freedom, you might try `module` or `amd` and see if it behaves better for you. So long as it still works with `online-go.com` I'm not picky, and I think `module` is supposed to be the way of the future so might try that first.

See https://github.com/online-go/goban/?tab=readme-ov-file#2-using-local-clone-of-goban-while-working-on-online-gocom for how to use your local repo in your project for development - just swap out `online-go.com` with your project. Also, if you're using `npm`, they have npm link stuff as well though slightly different way to call things iirc: https://docs.npmjs.com/cli/v10/commands/npm-link

**Comment by adamreisnz** [comment]
Well, as per my last comment, I've established in what circumstances it wasn't working, which was when it was loaded server side for SSR. So I take it this library just doesn't support running in Node, and is only built for the browser.

I've resolved it on my end by not using it for server side rendered components, which is fine.

**Comment by anoek** [comment]
Cool
