### ISSUE TITLE
Change GoEnginePlayerEntry.pro to boolean

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/goban#30]
Request: Change [GoEnginePlayerEntry.pro](https://github.com/online-go/goban/blob/be225ec15a99f65fd5794d52ac75c0f68aa39b74/src/GoEngine.ts#L84) to boolean.

Would this cause issues on the server side of OGS?  Currently, the front end treats it like a bool anyway:

        let pro = ev.target.value.indexOf(".1") > 0;    // result of comparison is boolean
        console.log(rank, pro);
        this.props.config.players.black.rank = rank;
        this.props.config.players.black.pro = pro;
        this.props.black.rank = rank;
        this.props.black.pro = pro;

Many similar examples in [GameInfoModal.tsx](https://github.com/online-go/online-go.com/blob/d0e87b841fef869428ff5b75e77a5f0442251f06/src/views/Game/GameInfoModal.tsx).  I ran into this when trying to add type information, in order to make [#1362](https://github.com/online-go/online-go.com/issues/1362) easier to solve.

**Comment by anoek** [comment]
I'm sorry for the delay on this, it slipped past my radar that it was sitting here. That change should be fine, it's a boolean field in the database already, not sure why it's not a boolean wherever it's popping out that you're seeing it, although I used to map booleans to 0/1 sometimes out of an old old habit - so that could account for it.

**Comment by BHydden** [comment]
> I used to map booleans to 0/1 sometimes out of an old old habit - so that could account for it.

Yep I can tell you the banning methods are split between true/false and 0/1 still :P haha
