### ISSUE TITLE
Roadmap / work left until 1.0?

### ISSUE THREAD

**Issue by Trevoke** [online-go/goban#82]
Hi,

I would like to leverage this for a project of mine; how much work is left until this is considered more widely usable?

With such a list I might also be able to contribute effort towards generalization of this codebase.

**Comment by anoek** [comment]
If you find it usable as is I think it's probably pretty safe to use. 

The main blocker for 1.0 is that it's not really friendly to drop in and use on a site for something like an SGF viewer, tsumego solver, or OGS game viewer in the sense that in order to do so you would have to do your own control buttons and that sort of stuff, which is a little more involved than what I figure most people want to do. So, I think what I'd like to do or see done is do a little react UI component for at least those basic use cases, some examples showing how to do it, how to style it, and work through all the different packaging targets that folks tend to want.  

If you're interested in working through that process with me it'd be nice to have a real world use case to consider and design around on the march to 1.0. I'm sure that'd be much better than me speculating and probably getting a lot of stuff wrong ;) Shoot me an email at anoek@online-go.com if you feel like sharing some details about your project and we can see what makes sense - it'd be nice to get 1.0 out there for sure.
